// <auto-generated />
using System;
using ClinicAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ClinicTrackerContext))]
    [Migration("20240514110412_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClinicAPI.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<float>("Experience")
                        .HasColumnType("real");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Age = 32,
                            DateOfBirth = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 5.5f,
                            Gender = "Male",
                            Name = "Pranav",
                            Specialization = "Dentist"
                        },
                        new
                        {
                            Id = 102,
                            Age = 51,
                            DateOfBirth = new DateTime(1954, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 2f,
                            Gender = "Male",
                            Name = "Tharun",
                            Specialization = "Sergeon"
                        },
                        new
                        {
                            Id = 103,
                            Age = 65,
                            DateOfBirth = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 7.5f,
                            Gender = "Male",
                            Name = "Raj",
                            Specialization = "Dentist"
                        },
                        new
                        {
                            Id = 104,
                            Age = 73,
                            DateOfBirth = new DateTime(1954, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 23f,
                            Gender = "FeMale",
                            Name = "Tom",
                            Specialization = "Sergeon"
                        },
                        new
                        {
                            Id = 105,
                            Age = 42,
                            DateOfBirth = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 1.5f,
                            Gender = "Male",
                            Name = "Seyon",
                            Specialization = "Dentist"
                        },
                        new
                        {
                            Id = 106,
                            Age = 76,
                            DateOfBirth = new DateTime(1954, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = 73f,
                            Gender = "FeMale",
                            Name = "Joe",
                            Specialization = "Dermatologist"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
